# GET http://localhost:3000/film/13

POST /film HTTP/1.1
Host: http://localhost:3000
Content-Type: application/json
Authorization: Bearer  

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}